### ISSUE TITLE
System.UriFormatException: Invalid URI: The Uri string is too long

### ISSUE THREAD

**Issue by santhosh250595** [kawansoft/AceQL.Client#8]
Hi,
Hope you are doing good.

I'm getting the below exception when my query has json data with length of 338525. Is there any alternate way to execute this.

**something wrong during query Execution
errorType: 0 / reason: Invalid URI: The Uri string is too long. / httpStatusCode: OK / exception: System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at System.Net.Http.FormUrlEncodedContent.Encode(String data)
   at System.Net.Http.FormUrlEncodedContent.GetContentByteArray(IEnumerable`1 nameValueCollection)
   at System.Net.Http.FormUrlEncodedContent..ctor(IEnumerable`1 nameValueCollection)
   at AceQL.Client.Src.Api.Http.HttpManager.<CallWithPostAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AceQL.Client.Api.Http.AceQLHttpApi.<ExecuteQueryAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AceQL.Client.Api.AceQLCommand.<ExecuteQueryAsStatementAsync>d__17.MoveNext()**

**Comment by ndepomereu** [comment]
Hi Santosh,

First reaction would be to say "Why would you need such a huge input query?", but I know this is not a very fertile answer. ;-)

Can you please explain what is your query content (insert, update, select) so that I understand the need? And why it is so huge?
A concrete sample/example would be appreciated.
Then I can evaluate what to do do.
(For now input query is buffer, which per nature is limited by the HTTP stack in use and that we don't control very much. Maybe we can change the buffer to a file...)

**Comment by santhosh250595** [comment]
Hi,
So my query is in the below format "select * from dbo.functionname(parameter1, parmeter2,..parameter10);". In that one of the parameter is a text containing html content of length 338525.

insert into dbo.tablename values(param1, jsonparam2) -> json param2 is of type text length 338525 also gives same Uri exception.

**Comment by ndepomereu** [comment]
Hi,
I have no immediate solution.
This would be a new development with a multipart request (file upload) and would impact both server and client SDK side. 
Please let me think about it.
